### ISSUE TITLE
Support React 17

### ISSUE THREAD

**Issue by MarkG-IEL** [DevExpress/devextreme-react#513]
### Steps to Reproduce:

1. Create a project with react 17.x as a dependency
2. Attempt to install devextreme 20.2

### Results You Received:
```
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.2.0" from devextreme-react@20.2.5
npm ERR! node_modules/devextreme-react
npm ERR!   devextreme-react@"20.2.5" from the root project
```

### Results You Expected:

Installation without warnings

NOTE: While the error talks about the issue being devextreme-react, the actual dependency is in this repo's package.json. It appears there may be an issue as enzyme-adapter-react-16 doesn't support react 17, and, not surprizing considering the name, may have to be changed out or added once https://github.com/enzymejs/enzyme/issues/2429 is closed. I have to say, their tagging scheme makes it difficult for products like this one to support multiple versions. This is the reason semantic versioning exists!

**Comment by LexDX** [comment]
Hi @MarkG-IEL,

We fixed this issue in v.21.1.3. Please refer to this report for more information:
[Popover - onClick event handlers in template elements do not work with React v17.0.0](https://supportcenter.devexpress.com/ticket/details/t941721/popover-onclick-event-handlers-in-template-elements-do-not-work-with-react-v17-0-0#)

**Comment by MarkG-IEL** [comment]
@LexDX Is there an ETA for the release of v21.1?

**Comment by LexDX** [comment]
@MarkG-IEL,

We have plans to release v21.1 the next week if it all goes according to plan.

**Comment by Tjayojo** [comment]
This is still an issue in v21.1.3

![image](https://user-images.githubusercontent.com/19380643/120414557-29a94780-c328-11eb-8972-fb5fbc290d35.png)

**Comment by calebfreeman** [comment]
Encountering the same issue with 21.1.3. Is there a fix?
